# /etc/ansible/configurar_rutas.yml
---
- name: Configurar rutas est치ticas en las m치quinas virtuales
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Agregar ruta est치tica a la red bridge para kube_network_02
      ansible.builtin.command:
        cmd: ip route add 192.168.0.0/24 via {{ gateway }}
      when: inventory_hostname in groups['kube_network_02']
      vars:
        gateway: 10.17.3.1
      ignore_errors: yes

    - name: Agregar ruta est치tica a la red bridge para kube_network_03
      ansible.builtin.command:
        cmd: ip route add 192.168.0.0/24 via {{ gateway }}
      when: inventory_hostname in groups['kube_network_03']
      vars:
        gateway: 10.17.4.1
      ignore_errors: yes
